#! /bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# install zsh
if sudo pacman -Qi zsh > /dev/null ; then 
	# install oh-my-zsh
	echo "Zsh is already installed"
else
	sudo pacman -S --noconfirm zsh
fi

# launch dotfile install
/bin/bash install

echo $BASEDIR/zsh/zshrc
if [ -d ~/.oh-my-zsh ]; then
  rm -rf ~/.oh-my-zsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi
