syntax on
set encoding=utf-8
set number
set tabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent
set autoread
set nocompatible              " required
set splitbelow
set splitright
au CursorHold * checktime

" Move between windows using hjkl
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Autoindent
filetype plugin indent on

" ctrlp
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
  Plugin 'gmarik/Vundle.vim'
  Plugin 'Valloric/YouCompleteMe'
call vundle#end()            " required

let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

filetype plugin indent on    " required
